### PR TITLE
feat(toast): copy button when toast message is too large

### PR DESCRIPTION
**Pull request by tibi77**
I tested this in another screen and it looks good because I don t know how to trigger an error inside the app.

Also, can i do a before and after selector inside the fuels CSS? and thus remove the toast.css file?

### CODE REVIEW

**Comment by tibi77** [comment]
@LuizAsFight can you do your add reviewers magic in here as well ?

**Comment by tibi77** [comment]
I can not link issues but this is related to #557

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
I think this should be done in `fuel-ui` side and benefit also other projects that might need a copy button in toast for wathever reason.

this PR and other project would just use an option 

for example
`toast.error(TEXT, { showCopy: true })` 


this is tracked in [FRO-129](https://linear.app/fuel-network/issue/FRO-129/allow-toast-to-have-copy-button)
for now I will add `blocked` here until waiting for the fuel-ui implementation

**Comment by luizstacio** [comment]
Closing this to move it to the fuel-ui repo.

**Pull request closed without merging**
