### PR TITLE
fix: learn more broken link

### LINKED ISSUE #1387: Learn more link broken
in the connect screen, the learn more link is broken:
1- hard to click, needs to hover on top part of text
2- when you click, it redirects you to home page.

Image

### PR DESCRIPTION
**Pull request by Spiral-Memory**
This PR fixes the issue of the "Learn More" link being shown while a connection request is being made. The problem of being unable to click "Learn More" properly was due to the overlapping of elements in the "Learn More" div and the button below it, to address it, i have removed -10px of margin. I have also added the homepage URL as an external link in "Learn More."

Kindly review the PR.

Attachments:

Screenshot from 2024-06-24 17-54-33

After suggested changes:

image

closes #1387

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Hey @LuizAsFight 
Please review this PR as well !
Thanks

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
hi @Spiral-Memory thanks for your contribution, let's change it, can you just remove the link  as it's not sending to anywhere useful for learning about the connection? 
just remove the "Learn More" link and we're good

thanks !

**Comment by Spiral-Memory** [comment]
> hi @Spiral-Memory thanks for your contribution, let's change it, can you just remove the link as it's not sending to anywhere useful for learning about the connection? just remove the "Learn More" link and we're good
> 
> thanks !

Hey @LuizAsFight ,

Sorry, I misunderstood the requirement earlier. I have made the changes accordingly and removed the "learn more" text. Please re-review this PR.

Thanks.

**Review by LuizAsFight — APPROVED** [review]

**Comment by LuizAsFight** [comment]
thanks for the contribution @Spiral-Memory

**Pull request merged**
