### PR TITLE
feat: add new menu items and remove extra animation from Menu

### LINKED ISSUE #435: Click outside the sidebar should close the menu
Currently, the only way to close the sidebar after opening it is by clicking on the cross button, Users should be able to close it by clicking outside the menu.

### LINKED ISSUE #474: Sidebar remove animation on sidebar opening
When opening the sidebar the component slides from right to left, but the items on the menu present an animation from bottom to top. This animation creates a strange feeling that bug movement is not necessary and should be removed.

### LINKED ISSUE #476: Add network link on sidebar
Currently is not possible to open the network management screen from the sidebar, only from the home page. We should add a link to the sidebar menu to open the network list.

### LINKED ISSUE #477: Add forum link on sidebar
Add to the Support section a link to the fuel forum.
Link: https://forum.fuel.network/c/fuel-wallet/15

### LINKED ISSUE #496: Add block-explorer on sidebar links
Add a link to the block explorer on the sidebar menu.

### PR DESCRIPTION
**Pull request by LuizAsFight**
This PR

- remove animation from inside components of Menu
- make center of MenuItems scrollable
- changes in Menu items
  - change from Activity to History
  - Add Networks
  - Add Block Explorer
  - support section
    - Add Forum

Closes #496
Closes #474
Closes #477
Closes #476 
Closes #435

### CODE REVIEW

**Review by luizstacio — APPROVED** [review]

**Review by luizstacio — CHANGES_REQUESTED** [review]
The removal of the animation should be just enough to fix the issue.
- The current code has made some significant changes to the MENU aspect. It looks bigger now.
- The sub-item is rendering over the other components.
 - The animation on the sub-items should be kept if possible.
 
 Current:
Screenshot 2023-01-27 at 04 07 35
PR Preview:
Screenshot 2023-01-27 at 04 06 43

**Comment by LuizAsFight** [comment]
@luizstacio let's remove the menu footer "Network Selected" section? as now we have the "Networks" link, and also have how to change directly in home

**Comment by luizstacio** [comment]
> @luizstacio let's remove the menu footer "Network Selected" section? as now we have the "Networks" link in Menu, and also have how to change directly in home

I think is good to have it there also, like we have account dropdown on home but also on the sidebar

**Review by luizstacio — CHANGES_REQUESTED** [review]
The network selector should be kept on bottom

Screenshot 2023-01-27 at 23 47 10

**Comment by LuizAsFight** [comment]
@luizstacio this is because we need to release `fuel-ui` change together.

this is fixed by removing <Box> wrapping children content in Drawer component -> https://github.com/FuelLabs/fuel-ui/pull/190

**Comment by LuizAsFight** [comment]
I will move this to draft while we wait release there then

**Review by luizstacio — APPROVED** [review]

**Pull request merged**
