### PR TITLE
refactor: test about account Loader

### PR DESCRIPTION
**Pull request by qqqzhch**
refactor: test about account Loader
- #295

### CODE REVIEW

**Comment by qqqzhch** [comment]
Don't know why Vercel — Authorization required to deploy.

**Comment by qqqzhch** [comment]
What should I do now? What can I do to continue to push this task through? @luizstacio

**Comment by luizstacio** [comment]
@qqqzhch just need to fix the CI that are failing

**Comment by qqqzhch** [comment]
> @qqqzhch just need to fix the CI that are failing

I've seen the error, I'll get the latest code and change it.

**Comment by qqqzhch** [comment]
Got the new code, followed the dev docs to start up and get the token from the faucet, all went very smoothly, no more configuration issues from the first time!

**Pull request closed without merging**
