### PR TITLE
feat: improve domain info

### LINKED ISSUE #481: Improve Domain Info on Connection Request
The current design only shows the domain of the website requesting a connection. This makes it difficult for the user to understand the information.

We should improve the website info preview by adding a favicon, title, and complete domain name.

[Dapp Integration #1 - Connect Request
](https://www.figma.com/file/uEckQY4EaQ5rXwyISg6d1g/Fuel-Wallet?node-id=118%3A11308&t=IhItfPWrUeAednFK-4)

### PR DESCRIPTION
**Pull request by tomiiide**
### what does this PR do?
This PR updates the domain information for the connection request screen.

closes #481 

Screenshot 2023-02-20 at 7 43 48 AM
Screenshot 2023-02-20 at 7 45 24 AM

### CODE REVIEW

**Review by luizstacio — CHANGES_REQUESTED** [review]
- The domain URL should be cut to the maximum with and add some ellipses.
- The Gap between cards will look better if they are equal
- Sometimes the favicon not loads, and I was not able to replicate
Screenshot 2023-02-20 at 10 22 06

**Comment by LuizAsFight** [comment]
`OriginDetails` story is not showing the favicon in PR deployed preview

image

**Comment by LuizAsFight** [comment]
spacing between cards should be set by parent's css `gap`, instead of in `styles.accountList`

image

**Comment by LuizAsFight** [comment]
left is figma, right is the connection screen

- different font sizes
- different spacing in card headers, favicon 
- keep same spacing as is now for permissions list

image

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
code looks good, few minor changes in prev comments

**Comment by tomiiide** [comment]
I've fixed the spacing problem, thanks for the sharp eyes @LuizAsFight /

Screenshot 2023-02-21 at 1 31 23 AM
Screenshot 2023-02-21 at 1 31 30 AM

**Comment by luizstacio** [comment]
The titles should have the same space, it looks like the bottom has less padding
Screenshot 2023-02-21 at 15 04 27

**Review by LuizAsFight — DISMISSED** [review]

**Review by luizstacio — APPROVED** [review]

**Pull request merged**
